services:
  db:
    image: mysql:8.4
    container_name: deploy-db-1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Bangkok
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
      - --default-time-zone=+07:00
    # ports:
    #   - "127.0.0.1:${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent",
        ]
      interval: 5s
      timeout: 3s
      retries: 20

  migrate:
    image: migrate/migrate:v4.18.3
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../back/migrations:/migrations:ro
    entrypoint:
      - migrate
      - -path=/migrations
      - -database=mysql://${DB_USER}:${DB_PASSWORD}@tcp(db:3306)/${DB_NAME}?multiStatements=true
      - up

  api:
    build: ../back
    restart: unless-stopped
    env_file: .env.prod
    depends_on:
      migrate:
        condition: service_completed_successfully

  web:
    build: ../front
    restart: unless-stopped
    environment:
      SITE_ADDRESS: ${SITE_ADDRESS}
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api

volumes:
  mysql_data:
  caddy_data:
  caddy_config:
